######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 5 00:00:53 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp
